spring.application.name=api-gateway
server.port=8080

# Service URLs (for Docker, use service names)
account.service.url=http://account-service:8081
transaction.service.url=http://transaction-service:8082
payment.service.url=http://payment-api:8083

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
